### ISSUE TITLE
Much larger memory size required?

### ISSUE THREAD

**Issue by ck37** [sjewo/readstata13#16]
Is it expected that loading the dataset in R may require much more memory than the dta filesize? E.g. I have a 21GB .dta file that requires 21gb of RAM in Stata, but balloons to about 100GB in R. Is there anything that I should do to resolve this, or is it just due to a different storage mechanism in R?

**Comment by sjewo** [comment]
Hi Chris!
I would expect some memory overhead due to the R data structures and additional attributes read.dta13() generates. We're inspecting this issue at the moment. Could you give us some information about your .dta file (number of rows and columns, type of data)?

**Comment by JanMarvin** [comment]
Any news on this one? We did look into it. Tested with some smaller (2.8 and 5.x GB) numeric data sets and it appeared as if R uses a few megabytes more to store the data. For instance the 2.8GB dta-file was imported to a 3GB R-object (`pryr::object_size()`). A cause for R to use more memory can be that Stata knows a few C-types R does not handle e.g. Stata has shorts, bytes and ints, R only has integers. Same goes with numerics, here Stata has floats and doubles. If the dta-file was written after calling `compress`, R blows some types up. If that is the case, there is nothing we can do about it.

Since the file grows that much, our main assumption is that it is the attributes that blow up the R-object. If your data consists of factors with multiple labels, the information is stored numerous times. Once in the data-matrix and once in the attributes field. In addition using `missing.type=T` will blow up the size of the R-object. With this option each variable is mirrored inside the data.frame attributes. The same thing happens if your file contains strls and you do not use `replace.strl=T`. In this case you end up with a numeric value stored in the data.matrix and the same value inside the attributes field next to the string containing the strls-text.

Without further knowledge of the dta-file and how it is imported, everything on our end is just guesswork. For starters you might begin stripping the resulting R-object from all unneeded attributes (saving it as Rdata, restarting R and loading the Rdata-file) to tackle memory problems.

Marvin
