### ISSUE TITLE
How does one add stata variable labels in ``save.dta13``?

### ISSUE THREAD

**Issue by kendonB** [sjewo/readstata13#24]

**Comment by JanMarvin** [comment]
Hey @kendonB ,
you can do it this way
```R
dd <- data.frame(x = 1:2, y = letters[1:2])

attr(dd, "var.labels") <- c("numerics", "characters")

library(readstata13)

save.dta13(data = dd, file = "/tmp/issue24.dta")

dat <- read.dta13(file = "/tmp/issue24.dta")

attr(dat, "var.labels")
```

Variable labels do not stick with a variable, so moving variables around in a data frame does not maintain the correct variable order (e.g. moving variable labels around after attaching the attributes `dd <- dd[c("y","x")]` will print variable label "numerics" for y and "characters" for z).

A word of caution, `lenght(attr(dd, "var.labels"))` must match `nrow(dd)` otherwise the attribute is ignored when writing, since incomplete variable labels would crash the rcpp function and filling it with empty strings did not look like a good choice.

hth
Marvin
