### ISSUE TITLE
Variable length limit

### ISSUE THREAD

**Issue by erikwestlund** [sjewo/readstata13#29]
Stata limits variable lengths to 32 characters. R does not.

If you save using this package and have long variable names, it will not truncate them. Stata (i'm using MP version 14) will load the, but cannot access those with too long names.

I'd recommend, ideally, an option on how to abbreviate (truncate/remove random characters/etc.)  I'd looka t how the foreign package does it.

**Comment by JanMarvin** [comment]
Thanks for the report. We already resize our variable names, but still we are a single nchar to long. I will push a fix to our master branch soon. To convert all spaces etc. to a Stata readable format in 0.8.2 convert.underscore was slightly improved.

**Comment by JanMarvin** [comment]
I did push another commit to master which checks on our R side the maximum characters allowed. We already have limits for earlier dta-file versions implemented. This new checks only apply to dta-version 117 and 118.

```R
x <- data.frame(x = 1)
names(x) <- paste0(letters, letters, collapse = "")
save.dta13(x, file = "/tmp/issue29.dta", version = 14)

z <- "ääääääääääääääääääääääääääääääääääääääääääääääääääääääääääääää"
names(x) <- z
save.dta13(x, file = "/tmp/issue29.dta", version = 14)
```

I can read both files and Stata can handle their varnames. Still I feel that truncating is not a pleasant way to go. If you really have to work with such long variable names truncation may lead to identical variable names, so maybe dropping respective varnames completely is a safer way to go. PR are welcome.
Nevertheless this issue is closed as far as I am concerned  and the fix will be in the next release.
