### ISSUE TITLE
make the 'file' argument to connection, not character

### ISSUE THREAD

**Issue by otoomet** [sjewo/readstata13#46]
I am using readstata13 for data interchange with other team members.  A few of the files we handle are rather large (>2G) and I prefer to keep it in the compressed format and just decompress on-the-fly as what you can do with read.table and friends.  However, readstata13 does not accept `file` argument to be a connection.  Can this feature be added?

And thank you for the package :-)

**Comment by sjewo** [comment]
Thanks for the suggestion! I'm not sure if its possible to use R connections, because the file is read in the C++ part. Maybe it is possible to create a temporary file from the connection.
We'll take a look into this issue.

**Comment by JanMarvin** [comment]
I have pushed an attempt to handle zip files in `read.dta13()` to our branch "connections". Handling of zip files containing dta-files is solved calling `unzip()` internally and extracting the zip-file to `tempdir()` and reading it from there. Currently there is no Rcpp solution for reading R connections. Since we read from files, we would not benefit from reading the information from a connection into a `Rcpp::RawVector` the way `readr` handles connections. We would just end up with a copy of the file in our memory, which we then would have to write and erase from our memory.

The current implementation is just for zip files, but could be extended to anything R can extract. Maybe you could have a look at it and tell me if this helpful to your problem @otoomet.

**Comment by JanMarvin** [comment]
Any update @otoomet ?

**Comment by JanMarvin** [comment]
Just found Jim Hesters package `archive` and had a quick view at the used approach. He manages to use connections in Rcpp (maybe we could borrow some of his code).

Anyway, my initial thought, that connections read everything into memory and access it from there (so that we would end up with several copy of the same data) appears to be wrong. Just testet connections with read.csv and archive and standard R connections. Looking at htop while running the tests shows that they both require the same amount of memory. Right now this appears to be dark magic, but it could be something to look into on some rainy day. Right now I do not really care and no one else seems to as well.

Still we would have to find a way to replace our c++::fopen parts with some R::connection stuff (which might or might not exist), but after all it might work?

```{R}
# n <- 20000
# m <- 650
#
# mm <- matrix(rnorm(n*m), ncol = m, nrow = n) # ~100 Mb
#
# write.csv(mm, file = "/tmp/mm.csv", row.names = FALSE)
# zip(zipfile = "/tmp/mm.csv.zip", files = "/tmp/mm.csv")

mm <- read.csv("/tmp/mm.csv")
# 
# devtools::install_github("jimhester/archive")
# # install.packages("tibble")

# default connection approach
mm <- read.csv(unz(description = "/tmp/mm.csv.zip", filename = "mm.csv"))

library(archive)
mm <- read.csv(archive_read("/tmp/mm.csv.zip"))
```

**Comment by otoomet** [comment]
Thanks, Jan and sjewo :-)

I was using 'haven' meanwhile (that one does on-the-fly decompression, I don't know how) but seems it cannot handle version 118 files.  You referred to the 'connection' branch, where can I find it?  I prefer bzip2 for my own work but just plain zip should give us most of the goodies of compression.

**Comment by JanMarvin** [comment]
@otoomet I did remove it the day before yesterday since you did not respond for two months or so. Is now back up. You can install it using `devtools` with: `devtools::install_github("sjewo/readstata13", ref = "connection")` iirc. Still feedback is required. I do not need this in my everyday life, so if you want something like that included, please give some feedback.
