### ISSUE TITLE
Respect already defined attributes on save

### ISSUE THREAD

**Issue by sjewo** [sjewo/readstata13#70]
I moved [this note](https://github.com/sjewo/readstata13/issues/69#issuecomment-638630201) by @jaySf into a new issue:
>  When attributes e.g. "datalabel" or "time.stap" were already defined, save.dta13 overwrites/deletes them, except "var.labels", without any warning.

Should we use already defined attributes for 
- time.stamp
- data.label
- var.labels ?

And what about the other attributes?

**Comment by JanMarvin** [comment]
Can't remember precisely what my intentions were, but I don't know if it's a good idea to use any of the attributes of an existing data.frame.

* Most likely you won't set the time.stamp at all, it was just added because I could.
* The data label might be preserved but then again, if we go from Stata to R and back, wouldn't we want to set a new name anyways?
* Labels are foreign to R and the handling of them is therefore at least incoherent. They are not attached to columns of a data.frame and might get lost doing R things. We'd have to keep track of the ordering of variables and labels to not mess something up. Labeled variables in tibbles might to be a better solution to the latter problem, but iirc their labels have a tendency to get lost too (and I wouldn't want to touch them with a ten foot pole)

Therefore I conclude it's not worth the hassle. If someone is really required to keep any of the above I'd say export the attributes and add them to the save function on your own risk

**Comment by jaySf** [comment]
@sjewo Thanks for outsourcing my note.

Actually @JanMarvin is right; I also think it is not necessary to change much. I had simply imported a .dta file from Stata with `read.dta13()` and saw all the attributes. I thought they should be set when exporting before using `save.dta13`, but actually it's `read.dta13()` that converts Stata information into attributes. The only thing: a warning could be thrown when attributes are in fact overwritten.

However, you may notice the inconsistency in defining the `"var.labels"`; they only can be set when using `attr(data, "var.labels") <- `, and perhaps `save.dta13()` could be improved for convenience by adding an argument `var.labels=` that expects a character vector of length `ncol(data)` that is used for the variable labels in Stata.

**Comment by jaySf** [comment]
Just a sidenote: I removed my Q/A on Stack Overflow since it's no longer applicable.

**Comment by JanMarvin** [comment]
I've added an option to include varnames as character vector in https://github.com/sjewo/readstata13/commit/ebbba64feb0871f340af1ca7c6582bf0965f850a

**Comment by JanMarvin** [comment]
@jaySf could you have a look if this fixes your problem and close the issue if so?

**Comment by JanMarvin** [comment]
Seems this is no longer relevant
