### ISSUE TITLE
Error when reading a .dta file in R

### ISSUE THREAD

**Issue by VioletteM** [sjewo/readstata13#74]
I’ve been trying to read a dta file in R (version 4.0.4) on a ubuntu 18.04 lts server using the “readstata13” library but it gives me the “Error in stata_read(filepath, missing.type, select.rows, select.cols, : First byte: Not a dta-file we can read.”

I’ve updated the library, removed and re-installed it...provided the absolute path to the file but still get the same error. I appreciate any help on this.

**Comment by sjewo** [comment]
Hi!

The file might be damaged. Does the file work in Stata?

Could you also do a test with our develeopment version:

```
install.packages("remotes")
remotes::install_github("sjewo/readstata13", ref="testing")
```

**Comment by VioletteM** [comment]
Hello, 

Yes it runs fine in stata. I also tried the test version but still get the same error.

**Comment by JanMarvin** [comment]
If you're unable to share the file, could you please elaborate on which Stata version the file was created, how you are importing it with Stata, on which operating system it was created and on which operating system are you trying to import it, etc.? Otherwise we are unable to help you.

Regarding the check that bails out, it simply reads the first byte. If it's `<` or any integer number (iirc, it's been a while since I programmed it).

**Comment by VioletteM** [comment]
It is a quite confidential file that i received from an external source in "dta" format. so it would be difficult to get the stata version in which the file was created. Decided to convert it to csv format. Thank you and i will get to the bottom of it once i get all info on version in which the file was created. Thanks again!

**Comment by JanMarvin** [comment]
Sure thing. Even if we couldn't help you straight away, we should tweak the output line to print the indicated file version. We can not simply override it, since Stata modified their file format a bunch of times. It's a saveguard against reading incorrect values.

Since I've reverse engineered quite a lot of these older Stata versions, I'm especially interested, if there is one out in the wild, that I've missed (version 1 maybe or a version 109? who knows). For now I'll close this issue, but please feel free to reopen it, once new information is available.
