### ISSUE TITLE
Save additional metadata to .dta

### ISSUE THREAD

**Issue by GitHunter0** [sjewo/readstata13#77]
Hi folks,

First, thank you for this package, it is really helpful to us.

I need to export other metadata to `.dta` file, however I could not find a way to do that.

For example, I tried to fill the `expansion.fields` attributes with some notes, nonetheless all metadata in `attributes()` (except the variable labels) were unavailable in the exported `.dta` file. See a MWE below:

```
library(tidyverse)
library( readstata13)

rdata <- mtcars[1:10, 1:4]
attributes(rdata)[["var.labels"]] <- c("vl1", "vl2", "vl3", "vl4")
attributes(rdata)[["datalabel"]] <- "Dataset Label"

expansion_fields <- list()

expansion_fields <- expansion_fields %>% 
  append(list(c("mpg","note1","note1 content for variable mpg"))) %>% 
  append(list(c("mpg","note2","note2 content for variable mpg")))

attributes(rdata)[["expansion.fields"]] <- expansion_fields

readstata13::save.dta13(rdata, file="test.dta")
```

So, is there a way for example to create an R dataframe and pass metadata that will be displayed in Stata's viewer `Notes` field?

Any help will be appreciated.

**Comment by JanMarvin** [comment]
Hello @GitHunter0,

there is a way to achieve this, but since neither of us had any use for it, we never developed a function for users to create these notes. It's been a long time since I had a look at this, but there is an example in one of our tests. If I remember correctly you need this `note0` part for anything you want to document either variables or the entire dataset.

https://github.com/sjewo/readstata13/blob/82b5647263d79be4dd8520ea0b5919dece9a468d/tests/testthat/test_save.R#L938-L945

**Comment by GitHunter0** [comment]
Hey @JanMarvin, it worked! Thank you for sharing this workaround.

**Comment by JanMarvin** [comment]
Great! Though, it's not really a workaround. It's more like that's how Stata handles things on their end (I just wrote the function on our end, that allows writing this list from R. Ideally there would be some function - on our end - helping the user to write this table, but there is so much to do and so little time :smile:
