### ISSUE TITLE
Reading long strings (strL's) into a character vector gets slow as number of rows increases - potential solution 

### ISSUE THREAD

**Issue by hans-elliott99** [sjewo/readstata13#87]
Hello.

I have been using `readstata13` for a project with a decently large dataset and noticed that read-times with `read.dta13` can be very slow, particularly in datasets that include "long string" (strL) type variables. Even if I read only a subset of the rows using the select.rows argument, I can not improve performance.
I pin-pointed the issue to be `readstata13`'s handling of Stata's strL type in the [read_dta c++ function in read_dta.cpp](https://github.com/sjewo/readstata13/blob/main/src/read_dta.cpp#L480). Specifically, using Rcpp::CharacterVector::push_back gets very slow as the vector increases in size.

One way to see this is to try and load a decently large dataset which contains a strL column, like the one created in my reprex below.
For starters, you can comment out [the calls to push_back on lines 565, 566](https://github.com/sjewo/readstata13/blob/main/src/read_dta.cpp#L565) to essentially ignore the saving of the strL's. Re-compile and notice that it takes much less time to load the dataset (although the strL column is full of NA's).

Even if one uses the select.rows argument, the current routine reads all of the strL's into the CharacterVector. I don't know enough about the DTA file format to know if this is avoidable. If it is not, my idea below offers a potential speed-up.

These examples are run on [my fork of the package](https://github.com/hans-elliott99/readstata13) which adds a few print statements to illustrate what is happening and implements the potential solution, which is just to use the number of strL type columns to pre-allocate the CharacterVectors.

Here the package is just compiled with some extra print statements (all edits in src/read_dta.cpp). Its behavior is identical to the behavior of the current CRAN package.
```R
devtools::load_all() # load/re-compile readstata13

# Create df which has a long string column
# Long strings - strL - are those with > 2045 chars
# (https://www.stata.com/features/overview/long-strings/)
N = 1e5
big_strl <- data.frame(
    x = 1:N,
    y = sample(LETTERS, N, replace = TRUE),
    z = c(paste(rep("a", 3000), collapse=""), sample(LETTERS, N-1, replace=TRUE))
)

# save.dta13 will save 'z' as type strL since it has a string w over 2045 chars
# (as would stata)
if (!file.exists("big_strl.dta"))
    readstata13::save.dta13(big_strl, "big_strl.dta")

# Even if we select 1 row, we still have to read all of the long strings
x <- readstata13::read.dta13("big_strl.dta", select.rows = 1)
#> [1] USESTRLFIX = 0
#> [1] 1 strLs detected
#> [1] reading long strings...
#> [1] 0: 0 secs (vec len = 1)
#> [1] 10000: 2 secs (vec len = 10001)
#> [1] 20000: 8 secs (vec len = 20001)
#> [1] 30000: 13 secs (vec len = 30001)
#> [1] 40000: 18 secs (vec len = 40001)
#> [1] 50000: 23 secs (vec len = 50001)
#> [1] 60000: 29 secs (vec len = 60001)
#> [1] 70000: 33 secs (vec len = 70001)
#> [1] 80000: 39 secs (vec len = 80001)
#> [1] 90000: 47 secs (vec len = 90001)
#> [1] done!
```

Here the package is compiled with my potential fix. I [pre-allocate the CharacterVectors](https://github.com/hans-elliott99/readstata13/blob/main/src/read_dta.cpp#L502) used to store the strL values (ie, the strings themselves) and their "names" . The number of strL columns is calculated [in the same loop that the vartypes are determined in](https://github.com/hans-elliott99/readstata13/blob/main/src/read_dta.cpp#L234). The CharacterVectors are initialized with size: (number of strL columns) * (nrows in data); the strL values and names are stored by slicing into these vectors rather than appending.
```R
devtools::load_all() # load/re-compile readstata13

# Create df which has a long string column
# Long strings - strL - are those with > 2045 chars
# (https://www.stata.com/features/overview/long-strings/)
N = 1e5
big_strl <- data.frame(
    x = 1:N,
    y = sample(LETTERS, N, replace = TRUE),
    z = c(paste(rep("a", 3000), collapse=""), sample(LETTERS, N-1, replace=TRUE))
)

# save.dta13 will save 'z' as type strL since it has a string w over 2045 chars
# (as would stata)
if (!file.exists("big_strl.dta"))
    readstata13::save.dta13(big_strl, "big_strl.dta")

# Even if we select 1 row, we still have to read all of the long strings
x <- readstata13::read.dta13("big_strl.dta", select.rows = 1)
#> [1] USESTRLFIX = 1
#> [1] 1 strLs detected
#> [1] reading long strings...
#> [1] 0: 0 secs (vec len = 100000)
#> [1] 10000: 0 secs (vec len = 100000)
#> [1] 20000: 0 secs (vec len = 100000)
#> [1] 30000: 0 secs (vec len = 100000)
#> [1] 40000: 0 secs (vec len = 100000)
#> [1] 50000: 0 secs (vec len = 100000)
#> [1] 60000: 0 secs (vec len = 100000)
#> [1] 70000: 0 secs (vec len = 100000)
#> [1] 80000: 0 secs (vec len = 100000)
#> [1] 90000: 0 secs (vec len = 100000)
#> [1] done!
```
The first example demonstrates a pretty substantial slowdown on my machine, even for this relatively small dataset. You could clone my fork and run `reprex.R` yourself to confirm. For the larger DTA datasets I work with, this makes importing painfully slow. And reading the file in chunks doesn't help since all of the strL's are read every time, regardless of select.rows.

If this is useful, I could clean up my fork and make a PR.

**Comment by JanMarvin** [comment]
Hi @hans-elliott99 , thanks for the very detailed issue. Indeed it's known that Rcpp::Vector push backs are slow. For every push back the previous vector is copied unlike in std::vector. I can have a look later if cleaning up your code takes to long. Otherwise it looks fine to me and I'd simply remove the defines.

Oh and maybe it was lost, but your potential fix solves the issue for you?

**Comment by JanMarvin** [comment]
I have opened a PR in #88 could you check if this solves the issue for you? You can install it like this:
`remotes::install_github("sjewo/readstata13#88")`.

Reading all the strls should not really slow down the entire import (unless ofc the file is way to big and contains multiple columns with strls, no rule w/o exception).

I used a slightly different approach, because I'm not sure if the `GSO` part, where the strls are located, is as long as the data frame. At least in theory duplicated strings could share a strl record and missings might not contain a record. We might run into new trouble assuming the number of the strls. I simply replaced the `Rcpp::CharacterVector`s to the memory efficient `std::vector<std::string>`s. At one point we have to copy from Rcpp to R, but this should now be limited to a single copy operation when we assign the values to `Rcpp::CharacterVector`.

Only possible drawbacks I can think of are non-unicode R sessions, where the encoding of `std::vector<std::string>` might differ compared to `Rcpp::CharacterVector`, though this problem should be negligible.

Potential room for improvement might be an option to skip reading the entire strl section if strl conversion is not wanted or if strl conversion is not required (only non strl columns are selected).

**Comment by hans-elliott99** [comment]
Hi @JanMarvin, thanks for looking into this. I tested #88 and using std::vector instead of Rcpp::CharacterVector definitely fixes my issue, speeding up a read.dta13 call that was taking at least an hour to just a matter of seconds.
Thanks!

**Comment by JanMarvin** [comment]
Thanks again for the report and the detailed issue!
